//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlehzeyMich {
            get {
                object obj = ResourceManager.GetObject("AlehzeyMich", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlehzeyPetrovi4 {
            get {
                object obj = ResourceManager.GetObject("AlehzeyPetrovi4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnneIoanovna {
            get {
                object obj = ResourceManager.GetObject("AnneIoanovna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnneLeo {
            get {
                object obj = ResourceManager.GetObject("AnneLeo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AnnePetrovna {
            get {
                object obj = ResourceManager.GetObject("AnnePetrovna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg1 {
            get {
                object obj = ResourceManager.GetObject("bg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ekaterine1 {
            get {
                object obj = ResourceManager.GetObject("Ekaterine1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ekaterine2 {
            get {
                object obj = ResourceManager.GetObject("Ekaterine2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EkaterineIoanovna {
            get {
                object obj = ResourceManager.GetObject("EkaterineIoanovna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ElizabethPetrovna {
            get {
                object obj = ResourceManager.GetObject("ElizabethPetrovna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EvdokiaLopukhina {
            get {
                object obj = ResourceManager.GetObject("EvdokiaLopukhina", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ivan5 {
            get {
                object obj = ResourceManager.GetObject("Ivan5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ivan6 {
            get {
                object obj = ResourceManager.GetObject("Ivan6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MariaMilosl {
            get {
                object obj = ResourceManager.GetObject("MariaMilosl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NataliaNarish {
            get {
                object obj = ResourceManager.GetObject("NataliaNarish", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Petr1 {
            get {
                object obj = ResourceManager.GetObject("Petr1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Petr2 {
            get {
                object obj = ResourceManager.GetObject("Petr2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Petr3 {
            get {
                object obj = ResourceManager.GetObject("Petr3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redCross {
            get {
                object obj = ResourceManager.GetObject("redCross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1730 г.: Взошла на престол Анна Ивановна при условии подписания особых “бумаг”, ограничивавших ее правление.
        ///Но когда планы Верховного Тайного совета стали достоянием общественности,
        ///Анна Ивановна разрушила “условия” и сохранила аристократическую форму правления. 
        ///Важные действия данного правителя:
        ///1730 г. — упразднение Верховного тайного совета.
        ///1731 г. — создание кабинета министров (Черкасский, Остерман, Головкин)
        ///1731 г. — отмена указа о единонаследии.
        ///1731 г. — создание Шляхетского сухопутного ка [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Анна_Иоановна {
            get {
                return ResourceManager.GetString("Анна Иоановна", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1725 г.: возведение на престол императрицы Екатерины I под наблюдением партии Меншикова. 
        ///Её не особо волновали государственные вросы,поэтому она создала специальный 
        ///орган --Верховный Тайный совет, который получил полномочия назначать высших чиновников,
        ///ведать финансами, руководить деятельностью Сената, Синода, коллегий, в состав вошли: 
        ///Меншиков, Апраксин, Головкин, Голицын, Остерман, П.А. Толстой. 
        ///Важные действия данного правителя: 
        ///1725 г. — открытие Академии наук.
        ///1725 г. — открытие Берингова п [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Екатерина_I {
            get {
                return ResourceManager.GetString("Екатерина I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1741 г.: возведение на престол императрицы Елизаветы Петровны при помощьи гвардейцев.
        ///Дочь Петра быстро избавилась от немцев в правительстве и вернулась к государственным принципам
        ///Петра Великого. Она продолжила &quot;дело&quot; отца. 
        ///Важные действия правителя:
        ///1744 г. — упорядочение системы налогообложения.
        ///1755 г. — основание Московского университета.
        ///1757 г. — учреждение Академии художеств.
        ///1756-1761 г. — участие России в Семилетней войне.
        ///___________________________
        ///	Елизавета Петровна выгодно отличалас [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Елизавета_Петровна {
            get {
                return ResourceManager.GetString("Елизавета Петровна", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1740 г.: Правление Ивана VI. Время его правллеия также называют периодом Бироновщины .
        ///Мальчику было несколько месяцев, так что фактическим правителем страны был регент Бирон -- 
        ///сподвижник Анны 	Иоановны. 
        ///Важные действия правителя:
        ///1741 г. — Ликвидация кабинета министров (его роль передаётся Сенату)
        ///1741 г. — создание личной императорской канцелярии.
        ///1741 г. — замена смертной казни каторгой.
        ///1741-1743 г. — война России со Швецией..
        /// </summary>
        internal static string Иван_VI {
            get {
                return ResourceManager.GetString("Иван VI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1727 г.: после смерти Екатерины, которую не очень волновали государственные вопросы,
        ///трон передается Петру II в обход других кандидатов. Ко времени смерти Петра II основные функции власти
        ///находились в руках Верховного Тайного совета.
        ///Важные действия правителя:
        ///1728 г. — прекращение строительства линейных кораблей.
        ///1728 г. — перенос столицы из Санкт-Петербурга в Москву..
        /// </summary>
        internal static string Пётр_II {
            get {
                return ResourceManager.GetString("Пётр II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1761: трон перешел к Петру III. Он не был патриотом. Как только он взошел на Российский престол,
        ///он остановил русские завоевания в Пруссии. Подписал соглашение с Фредрихом и разорвал
        ///союз России с Австрией и Францией. Император, не заинтересованный в политических пытках,
        ///пригрозил расформировать охрану, заявив, что подпишет закон, предусматривающий прекращение полиции безопасности. 
        ///А во внешней политике он отстранился от участия в Семилетней войны.  
        ///Важные действия правителя,
        ///которые послужили причи [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Пётр_III {
            get {
                return ResourceManager.GetString("Пётр III", resourceCulture);
            }
        }
    }
}
